spring.application.name=studentMS

server.port=8080

spring.datasource.url=jdbc:mysql://mysql-23de43cb-studentsmanagement.d.aivencloud.com:15500/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_qraWPTM0fVgpwtn_Ujo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
